handover/urls.py
from django.urls import path
from . import views

app_name = 'Handover'
urlpatterns = [
    path('', views.index, name='index'),
    path('maintenance', views.maintenance, name='maintenance'),
    path('signinuser/', views.signin, name='signin'),
    path('createuser/', views.createuser, name='createuser'),
    path('checkuser/',views.checkuser, name='checkuser'),
    path('showmyself/', views.showmyself, name='showmyself'),
    path('approve_user/', views.approve_user, name='approve_user'),
    path('approve_user_post/', views.approve_user_post, name='approve_user_post'),
    path('decline_user_post/', views.decline_user_post, name='decline_user_post'),
    path('updateuser/<int:user_id>', views.updateuser, name='updateuser'),
    path('user_state/<int:state_int>', views.user_state, name='user_state'),
    path('sendotp/', views.forgotpassword_send_otp, name='sendotp'),
    path('forgotpassword/', views.forgotpassword_post_otp, name='forgotpassword'),
    path('team/', views.team, name='team'),
    path('createteam/', views.createteam, name='createteam'),
    path('checkteam/', views.checkteam, name='checkteam'),
    path('updateteam/', views.updateteam, name='updateteam'),
    path('main/', views.main, name='main'),
    path('basictraining', views.basictraining, name='basictraining'),
    path('search', views.search, name='search'),
    path('newcomment/<int:handover_id>',views.newcomment,name='newcomment'),
    path('showHandoverModal',views.showHandoverModal, name='showHandoverModal'),
    path('showHandoverModalAttachments', views.showHandoverModalAttachments, name='showHandoverModalAttachments'),    
    path('attachment_modal', views.attachment_modal, name='attachment_modal'),
    path('createhandover/', views.createhandover, name='createhandover'),
    path('teammembers',views.teammembers, name='teammembers'),
    path('teammembers_user',views.teammembers_user, name='teammembers_user'),
    path('showhandover/<int:handover_id>',views.showhandover, name='showhandover'),
    path('updatehandover/<int:handover_id>',views.updatehandover, name='updatehandover'),
    path('activate/<int:handover_id>', views.activate, name='activate'),
    path('resolve/<int:handover_id>', views.resolve, name='resolve'),
    path('upload_attachment/<int:handover_id>', views.upload_attachment, name='upload_attachment'),
    path('send_feedback/', views.send_feedback, name='send_feedback'),
    path('logout', views.logout, name='logout'),
    path('test/',views.test,name='test'),
]  

#path('showHandoverModalTimeline', views.showHandoverModalTimeline, name='showHandoverModalTimeline'),

thpone/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('handover/', include('handover.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handover/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core import serializers
from django.core.mail import send_mail
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.hashers import *
from django.shortcuts import get_object_or_404
import random
import datetime
import pytz
#from django.core.paginator import Paginator

from .models import User, Team, Handover, Discussion, Changetype, Changestable, Logs, Teammember, Attachments

def registerChange(string,user,hand,com=None):
    # requires a comment for assingedsomeone, assignedspoc, changedassignee, changedspoc, changedticket
    chty = Changetype.objects.get(changetypename__iexact=string)
    if string == 'created':
        comment = 'Created a new handover'
    elif string == 'resolved':
        comment = 'Resolved the handover'
    elif string == 'commented':
        comment = 'Added a new comment: ' + com
    elif string == 'priority':
        comment = 'Changed the priority'
    elif string == 'lengthydescription':
        comment = 'Added a lengthy description'
    elif string == 'shorterdescription':
        comment = 'Shortened the description'
    elif string == 'changeddescription':
        comment = 'Changed the description'
    elif string == 'removeddescription':
        comment = 'Removed the description'
    elif string == 'activated':
        comment = 'Activated the handover'
    elif string == 'removedspoc':
        comment = 'Removed SPOC details'
    elif string == 'addedticket':
        comment = 'Added ticket # ' + com + ' to the handover'
    elif string == 'removedticket':
        comment = 'Removed the assigned ticket'
    elif string == 'changedticket':
        comment = 'Changed the ticket from ' + com
    elif string == 'shorttitle':
        comment = 'Shorter title: ' + com
    elif string == 'removedtitle':
        comment = 'Removed the title!'
    elif string == 'lengthytitle':
        comment = 'Added a lengthy title: ' + com
    elif string == 'changedtitle':
        comment = 'Changed the title to: ' + com
    elif string == 'assignedself':
        comment = 'Bravo! Assigned SPOC as self'
    elif string == 'assignedspoc':
        comment = 'Assigned ' + com + ' as SPOC'
        hand.new_spoc()
    elif string == 'changedspoc':
        comment = 'Changed SPOC from ' + com
        hand.new_spoc()
    elif string == 'attached':
        comment = 'Attached ' + com
    ch = Changestable(handover=hand,changedby=user,changetypeid=chty,changecomment=comment)
    ch.save()
    user.update_respect(chty.changetypeweight)

def logChange(string,loggedby=None,relatedto=None,team=None,com=None):
    chty = Changetype.objects.get(changetypename__iexact=string)
    if string == 'userapproved':
        comment = com + ' approved the user to join team.'
    elif string == 'userdeclined':
        comment = com + ' declined the user to join team.'
    elif string == 'passwordreset':
        comment = 'Changed password from **** to ****. Seriously?'
    elif string == 'requestjointeam':
        comment = 'Requested to join team'
    elif string == 'requestleaveteam':
        comment = 'Requested to leave the team'
    elif string == 'leftteam':
        comment = 'Left the team'
    elif string == 'activateduser':
        comment = 'Activated self'
    elif string == 'deactivateduser':
        comment = 'Deactivated self'
    elif string == 'activatedteam':
        comment = 'Activated team'
    elif string == 'deactivatedteam':
        comment = 'Deactivated team'
    elif string == 'changeduserfirstname':
        comment = 'Changed first name from ' + com
    elif string == 'changeduserlastname':
        comment = 'Changed last name from ' + com
    elif string == 'addeduserlastname':
        comment = 'Added ' + com + ' as last name'
    elif string == 'removeduserlastname':
        comment = 'Removed a last name'
    elif string == 'changeduseremail':
        comment = 'Changed user email ID from ' + com
    elif string == 'changedteamemail':
        comment = 'changed team email from ' + com
    elif string == 'changedteamname':
        comment = 'changed team name from ' + com
    elif string == 'completedbasictraining':
        comment = 'Completed the basic training module'
    elif string == 'removedfromteam':
        comment = 'Removed from team'
    log = Logs(logcomment=comment,logged_by=loggedby,related_user=relatedto,related_team=team,logtypeid=chty)
    log.save()

'''
Replace a set of multiple sub strings with a new string in main string.
'''
def replaceMultiple(mainString, toBeReplaces, newString):
    # Iterate over the strings to be replaced
    for elem in toBeReplaces :
        # Check if string is in the main string
        if elem in mainString :
            # Replace the string
            mainString = mainString.replace(elem, newString)
    
    return  mainString

def index(request):
    if 'h_user' not in request.session:
        teams = Team.objects.filter(is_active=True)
        if teams:
            context = {
                'teams': teams,
                }
            return render(request, 'handover/index.html', context)
        else:
            context = {
                'error_message':'No team exists right now. Please create one before using this application.',
            }
            return render(request,'handover/teamlogin.html', context)
    else:
        return redirect('Handover:main')

def maintenance(request):
    # get handovers resolved 30 days ago
    thirty_days = datetime.datetime.now(pytz.utc) - datetime.timedelta(days=30)
    sixty_days = datetime.datetime.now(pytz.utc) - datetime.timedelta(days=60)
    ninety_days = datetime.datetime.now(pytz.utc) - datetime.timedelta(days=90)
    hand = Handover.objects.filter(resolvedon__lt=thirty_days)
    hand.delete()
    users = User.objects.all()
    noteam = []
    nologon = []
    body = {
        'noteam': {
            'email': [],
            'thirty_days': [],
            'deleted': [],
        },
        'nologon': {
            'email': [],
        },
    }
    for u in users:
        if(len(u.team.filter(teammember__is_approved=True)) == 0):
            noteam.append(u.userid)
            body['noteam']['email'].append(u.useremail)
        if(u.last_logon < ninety_days):
            nologon.append(u.userid)
            body['nologon']['email'].append(u.useremail)
    if(len(noteam) != 0):
        for usrid in noteam:
            u = User.objects.get(pk=usrid)
            if(u.last_logon < thirty_days):
                u.state(False)
                body['noteam']['thirty_days'].append(u.useremail)
                if(u.last_logon < sixty_days and not u.user_is_active):
                    u.delete()
                    body['noteam']['deleted'].append(u.useremail)
    if(len(nologon) != 0):
        for uid in nologon:
            u = User.objects.get(pk=uid)
            u.delete()
    return JsonResponse(body)

def signin(request):
    teams = Team.objects.all()
    if request.method == 'POST':
        email = request.POST['signinemail']
        password = request.POST['signinpassword']
        if not email or not password:
            context = {
                'teams': teams,
                'error_message': 'Please fill in all the details',
            }
            return render(request, 'handover/index.html', context)
        else:
            if(User.objects.filter(useremail__iexact=email).exists()):
                if(check_password(password,User.objects.get(useremail__iexact=email).userpassword)):
                    u = User.objects.get(useremail__iexact=email)
                    u.logged_in()
                    request.session['h_user'] = u.userid
                    return redirect('Handover:main')
                else:
                    context = {
                        'teams': teams,
                        'error_message': 'Wrong password',
                    }
                    return render(request, 'handover/index.html', context)
            else:
                context = {
                    'teams': teams,
                    'error_message': 'User not found',
                }
                return render(request, 'handover/index.html', context)
    else:
        context = {
            'teams': teams,
            'error_message': 'Kindly fill the sign in form',
        }
        return render(request, 'handover/index.html', context)

def createuser(request):
    if request.method == 'POST':
        firstname = request.POST['signupfirstname']
        lastname = request.POST['signuplastname']
        email = request.POST['signupemail']
        password = request.POST['signuppassword']
        team = request.POST.getlist('signupteam')
        teams = Team.objects.filter(is_active=True)
        if not firstname or not email or not password or not team:
            context = {
                'teams': teams,
                'error_message': 'Please fill in all the details',
            }
            return render(request, 'handover/index.html', context)
        else:
            hash_pass = make_password(password)
            u = User(userfirstname=firstname,userlastname=lastname,useremail=email,userpassword=hash_pass)
            try:
                u.save()
                for t in team:
                    te = Team.objects.get(pk=t)
                    u.team.add(te)
                    _to = ['utkarsh.mehta@enpointe.io']
                    _from = 'ild@hms.com'
                    _subject = u.useremail + ' wants to join ' + te.teamname
                    _link_approve = 'https://handoverms.westus.cloudapp.azure.com:8000/handover/approve_user/?approval=True&team='+str(te.teamid)+'&user='+str(u.userid)
                    _link_decline = 'https://handoverms.westus.cloudapp.azure.com:8000/handover/approve_user/?team='+str(te.teamid)+'&user='+str(u.userid)

handover/templates/handover/ErrorPage.html
An error has occured.
<br/>
{{error_message}}<br/>
<a href="{{link}}">Click here</a> to go back.

handover/templates/handover/handover.html
{% extends 'handover/layout.html' %}

{% block navbar %}
<a class='nav-item nav-link' href='{% url "Handover:main" %}'>Home</a>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Hi, {{user_name.get_username}}
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{% url 'Handover:showmyself' %}?tab=home">Profile</a>
      <a class="dropdown-item" href="{% url 'Handover:logout' %}">Logout</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item disabled" href="#">Redeem your points</a>
    </div>
  </li>
{% endblock navbar %}

{% block body %}
<div class="container-fluid">
    <form method="post" action="{% url 'Handover:updatehandover' handover.handoverid %}" class="needs-validation">
        {% csrf_token %}
        <br/><div class='row justify-content-between'>
            <div class="col-4">
                <input type="submit" name='button_update' class="form-control btn btn-primary" value="Update"/>
            </div>
            <div class="col-4">
                {% if handover.status == 3 %}
                <a role="button" class="form-control btn btn-secondary" href="{% url 'Handover:activate' handover.handoverid %}">Activate this handover</a>
                {% else %}
                <a role="button" class="form-control btn btn-success" href="{% url 'Handover:resolve' handover.handoverid %}">Resolve this handover</a>
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                <label for="handoverTower" class="col-form-label">Team*:</label>
                <input class="form-control" disabled value="{{handover.tower}}" />
                <small class='text-muted'>We are working actively to let you change the team as well</small>
            </div>
            <div class="col-md-3">
                <label for="handoverSPOC" class="col-form-label">S.P.O.C.:</label>
                <select class="form-control" name="spoc" id="HandoverSPOC">
                    {% if handover.spoc %}
                    <option value="{{handover.spoc.userid}}">{{handover.spoc.get_username}}</option>
                    {% endif %}
                    <option value=''>-----------</option>
                    <!--option value="" selected>{handover.spoc}}</!--option -->
                    {% for user in users %}
                    <option value="{{ user.userid }}">{{ user.get_username }}</option>
                    {% endfor %}
                </select>
                <small class="text-form text-muted">Who's knows best about the handover?</small>
            </div>
            <div class="col-md-3">
                <label for="handoverPriority" class="col-form-label col-md-4">Priority</label>
                <select class="form-control" name="handoverPriority" id="HandoverPriority" required>
                    {% if handover.priority == 1 %}
                    <option value="1" selected>High</option>
                    <option value="2">Medium</option>
                    <option value="3">Low</option>
                    {% elif handover.priority == 2 %}
                    <option value="1">High</option>
                    <option value="2" selected>Medium</option>
                    <option value="3">Low</option>
                    {% elif handover.priority == 3 %}
                    <option value="1">High</option>
                    <option value="2">Medium</option>
                    <option value="3" selected>Low</option>
                    {% endif %}
                </select>
            </div>
            <div class="col-md-3">
                <label for="handoverTicket" class="col-form-label col-md-4">Ticket No</label>
                <input type="number" class="form-control" name="ticketno" id="ticketno" min="10000" max="999999999999999" value="{{handover.ticketno}}"/>
                <small class="text-form text-muted">Min: 5 digits | Max: 15 digits (for MS Cases)</small>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md">
                <label for="handoverDesription">Description:</label>
                <textarea maxlength="500" class="form-control" name="handoverDescription" id="HandoverDescription" rows="3">{{handover.description}}</textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="handoverDiscussions">Comments</label><br />
            <textarea class="form-control col-md-6" rows="3" name="handoverdiscussion" id="HandoverDiscussion" maxlength="100"></textarea>
            {% if discussion %}
                {% for d in discussion %}
                    <p class="text-muted">{{d.discussiontime}}: {{d.createdby}}: {{d.discussiontext}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <hr />
        {% if message %}
            <p>{{message}}</p>
        {% endif %}
        <div class='row justify-content-between'>
            <div class="col-4">
                <input type="submit" name='button_update' class="form-control btn btn-primary" value="Update"/>
            </div>
            <div class="col-4">
                {% if handover.status == 3 %}
                <a role="button" class="form-control btn btn-secondary" href="{% url 'Handover:activate' handover.handoverid %}">Activate this handover</a>
                {% else %}
                <a role="button" class="form-control btn btn-success" href="{% url 'Handover:resolve' handover.handoverid %}">Resolve this handover</a>
                {% endif %}
            </div>
        </div>
        <br />
    </form>
</div>
{% endblock body %}
{% block scripts %}
<script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
</script>
{% endblock scripts %}

handover/templates/handover/search_output.html
{% extends 'handover/layout.html' %}
{% block navbar %}
<a class='nav-item nav-link mr-auto' href='{% url "Handover:main" %}'>Home</a>
<form class="form-inline my-2 my-lg-0" action="{% url 'Handover:search' %}" method="GET">
    <input class="form-control mr-sm-2" type="search" placeholder="Description and comment." name="search_string" aria-label="Search">
    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
</form>
{% endblock navbar %}
{% block body %}
<div class="container-fluid">
    <h1 class="mt-3">Showing results for <span class="text-capitalize">'{{search_string}}'</span></h1>
    <fieldset>
        {% if h_description %}
        <legend>Found in Description</legend>
        <ul>
            {% for h_d in h_description %}
            <li>
                <a href="{% url 'Handover:showhandover' h_d.handoverid %}">{{h_d.description}}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>Not found in any description.</p>
        {% endif %}
    </fieldset>

    <fieldset></fieldset>
        {% if comments %}
        <legend>Found in comments</legend>
            <table class='table'>
                <thead>
                    <th>Comment</th>
                    <th>Handover</th>
                </thead>
                <tbody>
                    {% for com in comments %}
                    <tr>
                        <td>{{com.discussiontext}}</td>
                        <td><a href="{% url 'Handover:showhandover' com.handoverid.handoverid %}">{{com.handoverid.get_title}}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Not found in any comment.</p>
        {% endif %}
    </fieldset>
</div>
{% endblock body %}

handover/templates/handover/team_join.html
{% extends 'handover/layout.html' %}

{% block body %}
{% if error_message %}
    {{ error_message }}
{% else %}
<h1 class="display-2 text-center"><abbr title="Just some three random alphabets">I.L.D.</abbr></h1>
<h1 class="display-4 text-center">Join Team</h1>
<div class="container-fluid" style="max-width: 450px;">
    <div class="card text-center text-dark border-primary">
        <div class="card-body">
            {% if approval == 'True' %}
            <form class="needs-validation" name="approveUserForm" id="userapprove" action="{% url 'Handover:approve_user_post' %}" method="post" novalidate>
            {% csrf_token %}
            {% else %}
            <form class="needs-validation" name="approveUserForm" id="userapprove" action="{% url 'Handover:decline_user_post' %}" method="post" novalidate>
            {% csrf_token %}
            {% endif %}                
                <div class="form-group">
                    <label for="createTeamName">Your Email ID*:</label>
                    {% if current_user %}
                    <input type="email" class="form-control" placeholder="Your email ID" maxlength="350" name="approveuseremail" id="approvedUserEmail" value="{{current_user.useremail}}" required />
                    {% else %}
                    <input type="email" class="form-control" placeholder="Your email ID" maxlength="350" name="approveuseremail" id="approvedUserEmail" value="utkarsh.mehta@enpointe.io" required />
                    {% endif %}
                    <small class="form-text text-left">Maximum character length: 350</small>
                    <div class="invalid-feedback">Please enter your email ID</div>
                </div>
                <div class="form-group">
                    <label for="approveTeamLabel">Team</label>
                    <input class="form-control" type="hidden" name="approveteam" value="{{team.teamid}}" required />                    
                    <input class="form-control" type="text" name="approveteamname" value="{{team.teamname}}" required disabled/>
                    <label for="approveUserLabel">User</label>
                    <input class="form-control" type="hidden" name="approveuser" value="{{user.userid}}" required />
                    <input class="form-control" type="text" name="approveusername" value="{{user.get_username}}" required disabled />
                </div>
                <div class="form-group text-center">
                    {% if approval == 'True' %}
                    <button type="submit" class="form-control btn btn-primary">Approve</button>
                    {% else %}
                    <button type="submit" class="form-control btn btn-danger">Decline</button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock body %}

{% block scripts %}
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict';
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    //console.log(team_check)
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>
{% endblock scripts %}

handover/templates/handover/teamlogin.html
{% extends 'handover/layout.html' %}

{% block navbar %}
<a class="nav-item nav-link" href="{% url 'Handover:index' %}">Home</a>
{% endblock navbar %}

{% block body %}

<h1 class="display-2 text-center"><abbr title="Just some three random alphabets">I.L.D.</abbr></h1>
<h1 class="display-4 text-center">Team Sign Up</h1><br />
{% if message %}
<p class='text-success text-center'>{{message}}<a href="{% url 'Handover:index' %}">index page.</a></p>
{% endif %}
{% if error_message %}
<p class='text-danger text-center'>{{error_message}}</p>
{% endif %}
<div class="container-fluid" style="max-width: 540px;">
    <div class="card text-dark border-primary">
        <div class="card-body">
            <form class="needs-validation" name="newUserForm" id="teamSignUp" action="{% url 'Handover:createteam' %}"
                method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="createTeamEmail">Team Email*</label>
                    <input type="text" class="form-control" placeholder="Your team email..." autofocus maxlength="200" name="TeamEmail" id="createTeamEmail" required />
                    <small id="email_result" class="text-danger"></small>
                    <small id="ajax_load_message_teamemail" class="form-text text-dark"></small>
                    <small class="form-text">Maximum character length: 200</small>
                    <small class='form-text'>This app sends mails to teams, please enter a valid email ID</small>
                    <div class="invalid-feedback">Please enter the team email ID</div>
                </div>
                <div class="form-group">
                    <label for="createTeamName">Team Name*</label>
                    <input type="text" class="form-control" placeholder="Your team name..." maxlength="100" name="TeamName" id="createTeamName" required />
                    <small class="form-text">Maximum character length: 100</small>
                    <div class="invalid-feedback">Please enter the team name</div>
                </div>
                <div class="form-group text-center">
                    <button type="submit" id="createteambutton" class="form-control btn btn-primary">Create Team</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

{% block scripts %}
<script>
    $('#createTeamEmail').change(function () {
        $("#ajax_load_message_teamemail").html("Checking email availability. Please wait...");
        var email = $("#createTeamEmail").val();
        //console.log(email);
        $.ajax({
            url: '{% url "Handover:checkteam" %}',
            type: 'GET',
            data: { email: email },
            dataType: 'json',
            success: function (data) {
                if(data.is_taken) {
                    $("#email_result").html("This email is already taken by " + data.team_name);
                    $("#ajax_load_message_teamemail").html("");
                }
                else {
                    $("#email_result").html("")
                    $("#ajax_load_message_teamemail").html("Email ID can be used");
                }
            }
        });
    });

</script>
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict';
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    var team_check = $("#email_result").html()
                    //console.log(team_check)
                    if (team_check != '' || form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>
{% endblock scripts %}

handover/templates/handover/testingpage.html
Testing page